# Generated by Django 4.0 on 2022-01-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hsi_feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('diagnosis', models.CharField(max_length=100)),
                ('image', models.ImageField(height_field=200, upload_to='hsi_images', width_field=200)),
                ('datasize', models.IntegerField()),
                ('frames', models.IntegerField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
