# Generated by Django 4.0 on 2022-01-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_database', '0002_remove_hsi_feature_frames_remove_hsi_feature_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hsi_feature',
            name='offer',
        ),
        migrations.AddField(
            model_name='hsi_feature',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
