# Generated by Django 4.0 on 2022-02-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_database', '0004_address_diagnosis_history_hs_image_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='diagnosis_hist',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='spectral_image',
        ),
        migrations.AddField(
            model_name='address',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.patient'),
        ),
        migrations.AddField(
            model_name='diagnosis_history',
            name='patient',
            field=models.ManyToManyField(blank=True, null=True, to='imaging_database.Patient'),
        ),
        migrations.AddField(
            model_name='hs_image',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.patient'),
        ),
        migrations.AlterField(
            model_name='diagnosis_history',
            name='diagnosis',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.FloatField()),
                ('spectral_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.hs_image')),
            ],
        ),
        migrations.CreateModel(
            name='RGB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spectral_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.hs_image')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesize', models.IntegerField()),
                ('resolution', models.FloatField()),
                ('band', models.IntegerField()),
                ('bandpassrange', models.CharField(max_length=100)),
                ('frame', models.IntegerField()),
                ('spectral_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.hs_image')),
            ],
        ),
        migrations.CreateModel(
            name='Imaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_type', models.CharField(max_length=100)),
                ('light_intensity', models.FloatField()),
                ('magnification', models.FloatField()),
                ('focal_length', models.FloatField()),
                ('spectral_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.hs_image')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.address')),
                ('spectral_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.hs_image')),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=100)),
                ('spectral_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.hs_image')),
            ],
        ),
    ]
