# Generated by Django 4.0 on 2022-02-09 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_database', '0005_remove_patient_address_remove_patient_diagnosis_hist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.ImageField(blank=True, upload_to='mask/')),
                ('spectral_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.hs_image')),
            ],
        ),
        migrations.RemoveField(
            model_name='environment',
            name='spectral_image',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='address',
        ),
        migrations.RemoveField(
            model_name='software',
            name='spectral_image',
        ),
        migrations.AddField(
            model_name='address',
            name='hospital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='imaging_database.hospital'),
        ),
        migrations.AddField(
            model_name='environment',
            name='imaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.imaging'),
        ),
        migrations.AddField(
            model_name='rgb',
            name='rgb',
            field=models.ImageField(blank=True, null=True, upload_to='RGB/'),
        ),
        migrations.AddField(
            model_name='software',
            name='imaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.imaging'),
        ),
        migrations.CreateModel(
            name='Tissue_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(max_length=100)),
                ('annot_mask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.mask')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('annot_mask', models.ManyToManyField(blank=True, to='imaging_database.Mask')),
            ],
        ),
        migrations.CreateModel(
            name='Light_source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_source', models.CharField(max_length=100)),
                ('imaging', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.imaging')),
            ],
        ),
        migrations.CreateModel(
            name='Label_library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('tissue_class', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.tissue_class')),
            ],
        ),
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('professional_title', models.CharField(max_length=100)),
                ('annot_mask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.mask')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diag_type', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('description', models.TextField()),
                ('annot_mask', models.ManyToManyField(blank=True, to='imaging_database.Mask')),
                ('patient', models.ManyToManyField(blank=True, to='imaging_database.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('imaging', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.imaging')),
            ],
        ),
        migrations.CreateModel(
            name='Date_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('imaging', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.imaging')),
            ],
        ),
        migrations.CreateModel(
            name='Class_feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(max_length=100)),
                ('tissue_class', models.ManyToManyField(blank=True, to='imaging_database.Tissue_class')),
            ],
        ),
        migrations.CreateModel(
            name='Annot_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('annot_mask', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.mask')),
            ],
        ),
        migrations.CreateModel(
            name='Annot_file_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=100)),
                ('software_version', models.CharField(max_length=100)),
                ('annot_mask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.mask')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='examiner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.examiner'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.examiner'),
        ),
    ]
