# Generated by Django 4.0 on 2022-02-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_database', '0006_mask_remove_environment_spectral_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='mask',
            field=models.ImageField(upload_to='mask'),
        ),
        migrations.AlterField(
            model_name='rgb',
            name='rgb',
            field=models.ImageField(default=0, upload_to='RGB'),
            preserve_default=False,
        ),
    ]
