# Generated by Django 4.0 on 2022-02-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_database', '0007_alter_mask_mask_alter_rgb_rgb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='spectral_image',
        ),
        migrations.RemoveField(
            model_name='imaging',
            name='spectral_image',
        ),
        migrations.RemoveField(
            model_name='mask',
            name='spectral_image',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='spectral_image',
        ),
        migrations.RemoveField(
            model_name='rgb',
            name='spectral_image',
        ),
        migrations.DeleteModel(
            name='HS_image',
        ),
    ]
