# Generated by Django 4.0 on 2022-02-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_database', '0010_category_microscope_remove_patient_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgb',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
