# Generated by Django 4.0 on 2022-03-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_database', '0012_rgb_gray'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hs_image',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='rgb',
            name='spectral_image',
        ),
        migrations.AddField(
            model_name='hs_image',
            name='rgb',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.rgb'),
        ),
        migrations.AddField(
            model_name='rgb',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.patient'),
        ),
    ]
