# Generated by Django 4.0 on 2022-03-12 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_database', '0013_remove_hs_image_patient_remove_rgb_spectral_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hs_image',
            name='gray',
            field=models.ImageField(default=0, upload_to='gray/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hs_image',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.patient'),
        ),
        migrations.AlterField(
            model_name='hs_image',
            name='rgb',
            field=models.ImageField(default=2, upload_to='RGB/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RGB',
        ),
    ]
