# Generated by Django 4.0 on 2022-03-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_database', '0014_hs_image_gray_hs_image_patient_alter_hs_image_rgb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hs_image',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
