# Generated by Django 4.0 on 2022-03-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_database', '0015_hs_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='spectralImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spectralimage', models.ImageField(upload_to='hsi_images/')),
                ('rgb', models.ImageField(upload_to='RGB/')),
                ('gray', models.ImageField(upload_to='gray/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.category')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.patient')),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='spectral_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.spectralimage'),
        ),
        migrations.AlterField(
            model_name='imaging',
            name='spectral_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.spectralimage'),
        ),
        migrations.AlterField(
            model_name='mask',
            name='spectral_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.spectralimage'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='spectral_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.spectralimage'),
        ),
        migrations.DeleteModel(
            name='HS_image',
        ),
    ]
