# Generated by Django 4.0 on 2022-03-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_database', '0017_tissue_class_classimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='mask',
            field=models.ImageField(upload_to='MASK/'),
        ),
    ]
