# Generated by Django 4.0 on 2022-04-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_database', '0018_alter_mask_mask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectralimage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='spectralimage',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='spectralimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='spectralimage',
            name='gray',
        ),
        migrations.RemoveField(
            model_name='spectralimage',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='spectralimage',
            name='rgb',
        ),
        migrations.RemoveField(
            model_name='spectralimage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='spectralimage',
            name='spectralimage',
        ),
        migrations.RemoveField(
            model_name='spectralimage',
            name='uniqueId',
        ),
    ]
