# Generated by Django 4.0 on 2022-04-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_database', '0020_spctimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='spctimg',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
