# Generated by Django 4.0 on 2022-04-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_database', '0021_spctimg_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spctimg',
            name='description',
        ),
        migrations.RemoveField(
            model_name='spctimg',
            name='name',
        ),
        migrations.AddField(
            model_name='spctimg',
            name='diagnosis',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='spctimg',
            name='patient',
        ),
        migrations.AddField(
            model_name='spctimg',
            name='patient',
            field=models.ManyToManyField(blank=True, to='imaging_database.Patient'),
        ),
    ]
