# Generated by Django 4.0 on 2022-04-16 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_database', '0022_remove_spctimg_description_remove_spctimg_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectralimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_database.category'),
        ),
        migrations.AddField(
            model_name='spectralimage',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spectralimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spectralimage',
            name='gray',
            field=models.ImageField(default=2, upload_to='gray/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spectralimage',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spectralimage',
            name='rgb',
            field=models.ImageField(default=2, upload_to='RGB/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spectralimage',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='spectralimage',
            name='spectralimage',
            field=models.ImageField(default=1, upload_to='hsi_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spectralimage',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='spctImg',
        ),
    ]
